baseURL = 'https://bio.lmcly.fyi'
languageCode = 'en-us'
title = 'Lee Macaulay'

[params]
avatar = "/img/avatar.webp"
username = "Lee Macaulay"
networks = ["twitter","github"]

[params.social]
twitter = "lmcly"
github = "leemacaulay"

[params.social.base]
twitter = "https://www.twitter.com/"
github = "https://www.github.com/"