baseURL = 'https://bio.lmcly.fyi'
languageCode = 'en-us'
title = 'Lee Macaulay'

[params]
avatar = "/img/avatar.webp"
username = "Lee Macaulay"
networks = ["twitter", "instagram" ,"github", "mastodon"]

[params.social]
twitter = "lmcly"
github = "leemacaulay"
instagram = "ljmcly"
mastodon = "@lmcly"

[params.social.base]
twitter = "https://www.twitter.com/"
github = "https://www.github.com/"
instagram = "https://www.instagram.com/"
mastodon = "https://mastodon.social/"

[params.social.attr]
twitter = "noopener me"
github = "noopener"
instagram = "noopener"
mastodon = "noopener me"